### ISSUE TITLE
Number-based Category tagging in a tags.txt

### ISSUE THREAD

**Issue by myalow** [reluce/szurubooru-toolkit#30]
Hi,

Just wrote a script to convert all exported tags from my old hydrus instance into a format szurubooru-toolkit could import, and I followed the documentation [here](https://github.com/reluce/szurubooru-toolkit#label-create-tags), where it says to format <tag_name>,<tag_number>. Upon doing this in my text file, the script immediately throws up a large error ended with **Exception: Tag category '0' not found.**. As soon as I find and replace ", 0" to ", default", it works fine, now throwing up **category '3' not found**. It's not a huge issue, and it's a relatively easy fix on my end, but it does seem a bit confusing, following the documentation.

**Comment by reluce** [comment]
Thanks for pointing that issue out. I just checked locally and indeed, the category name has to be specified instead of its number. I updated the Readme file according to that.

Cheers!
