### ISSUE TITLE
upload-media defaults

### ISSUE THREAD

**Issue by BiscuitHub** [reluce/szurubooru-toolkit#33]
Hello,

Is there a way to change the default setting to safe instead of unsafe when uploading using the upload-media script?

Regards,

**Comment by BiscuitHub** [comment]
My non-tech-smooth-brain poked around a bit and changed the script because I couldn't figure it out with config.toml or cli arguments. This should work for me so I'll close this up and link the line I changed on my install.

https://github.com/reluce/szurubooru-toolkit/blob/8b80181e1bbcc77cc68ed843237a66756a8c3cfe/src/szurubooru_toolkit/scripts/upload_media.py#L117

For reference, I'm using it in Docker and just sent in that one file with a mount.

**Comment by reluce** [comment]
Good suggestion, I added the option `default_safety` to the `config.toml` file. It's included in the tag 0.7.7 and in the newest release on Docker Hub. Cheers!
