### ISSUE TITLE
Twitter config options still expected

### ISSUE THREAD

**Issue by shibaobun** [reluce/szurubooru-toolkit#40]
as part of [this commit](https://github.com/reluce/szurubooru-toolkit/commit/21919d6cf39f8ebfef107c6583acefe41fa45367), the `[twitter]` section in config.toml has been removed, but it seems like the [code checking for that option is still there](https://github.com/reluce/szurubooru-toolkit/blob/a02790e6ef25f35a114b250ebf0d3a8813f94db1/src/szurubooru_toolkit/config.py#L95C3-L95C3)

sorry i am not making a pr because i am also lazy -3-

**Comment by reluce** [comment]
Thanks for the info, I might have jumped the gun there 😅 . I added the options back in 6ebe250ea546c6b2ed56bafe4a90768783488962.
