### ISSUE TITLE
SauceNao autotagger - 'object is not iterable' error

### ISSUE THREAD

**Issue by Kalidibus** [reluce/szurubooru-toolkit#41]
It seems like with certain posts I get this error. Retrying the post doesn't change the error. Other posts can be tagged just fine. 

Command is simply: `auto-tagger "id:123"` or `auto-tagger "tag-count:0"`

On version 0.9

![image](https://github.com/reluce/szurubooru-toolkit/assets/93565603/78c74b87-e065-42a7-b4ac-4588db76b095)

**Comment by reluce** [comment]
I just pushed a possibly fix to `main`. I tried to reproduce your issue, but couldn't. Is there a way you can test it without a new version? Otherwise I put one up later today.

**Comment by Kalidibus** [comment]
It seems to be quite common on my end. It's hard to tell which post it's stuck on, but I'll try to find it to see if you hit the same thing with the particular post.

To test on main: do I just update the docker-config.yaml line `image: reluce/szurubooru-toolkit` to `image: reluce/szurubooru-toolkit:main`?

**Comment by reluce** [comment]
Docker Images won't get built unless there's a new tag for it, so i just pushed 0.9.1. You can use that or just the latest tag and it should pull just fine.

**Comment by Kalidibus** [comment]
So far so good! It's running through fine whereas right before updated the same query was getting the iterable error. Up to about a hundred without issue now.
