### ISSUE TITLE
Feature Request: Option to keep existing tags when using auto-tagger

### ISSUE THREAD

**Issue by Kalidibus** [reluce/szurubooru-toolkit#42]
When I use auto-tagger to tag a post with Saucenao results, it appears to remove any existing tags and replaces them fully with the new ones. 

There are instances where I have custom tags, and it would be good to keep those, but still be able to use auto-tagger. Could this be an option in the config file?

**Comment by reluce** [comment]
Hm, it should always keep the previous set tags. I also tried to reproduce it just now, but the script preserved the previous tag just fine.

Is it happening on all of your posts or just one? Is it a video/image? How many tag did you manually set?

Following lines are responsibly to keep the tags:
https://github.com/reluce/szurubooru-toolkit/blob/0255ca4ab4c3b10de6e680316bb1f92500a0d556/src/szurubooru_toolkit/scripts/auto_tagger.py#L299-L305

**Comment by Kalidibus** [comment]
Very sorry - this was user error on my part. I had a couple examples but realized different reasons on my end why I was seeing the old tags disappear (in some cases, I just straight up didn't notice them because I was looking for a different name).
