### ISSUE TITLE
--add-tags at time of import-from-url?

### ISSUE THREAD

**Issue by Kalidibus** [reluce/szurubooru-toolkit#56]
If I import something using "import-from-url" is there a way to add tags to the new post at the same time?

If not: is there a way to add-tags to the newest I'd post only, so I could just add this into a bash script or something?

**Comment by reluce** [comment]
I added the option `--add-tags` in the linked branch `1.0.2`. I will merge it in a few days, but in the meantime you can test it out there.

**Comment by reluce** [comment]
Added in `1.0.2`.
