### ISSUE TITLE
gallery-dl username and password options

### ISSUE THREAD

**Issue by Arthur-K-99** [reluce/szurubooru-toolkit#59]
Is there a way to pass either through cli or the config the username and password like in gallery-dl?
```
gallery-dl -u "<username>" -p "<password>" "URL"
```

Mainly for websites that cookies/authentication methods change all the time like sankaku.

**Comment by ItsKaa** [comment]
You can modify your gallery-dl config file, see https://github.com/mikf/gallery-dl?tab=readme-ov-file#username--password

**Comment by Arthur-K-99** [comment]
Oh ok, so when szurubooru-toolkit calls gallery-dl, it still looks for it's config. Thanks!
